# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    - mkdir .static
    - cp -r * .static
    - mv .static static
  artifacts:
    paths:
      - static
  only:
    - master